apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole-namespace-reader.yaml
  - clusterrole-secret-reader.yaml
  - clusterrole-secret-admin.yaml
  - clusterrolebinding-namespace-reader.yaml
