apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sa.yaml
  - rolebinding-secret-reader.yaml
  - limit-range.yaml
  - resource-quota.yaml
  - networkpolicy-default-deny.yaml
