apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../shared/roles
  - ../../shared/policies
  - apps
  - networking
  - rbac
  - namespaces/team-1/namespace.yaml
  - namespaces/team-1/sa.yaml
  - namespaces/team-1/rolebinding-secret-reader.yaml
